### ISSUE TITLE
怎么用呢

### ISSUE THREAD

**Issue by tangxu00** [rockcarry/ffjpeg#1]

**Comment by rockcarry** [comment]
编译运行即可

**Comment by rockcarry** [comment]
刚测试过，编码解码都是 ok 的

**Comment by rockcarry** [comment]
编译方法

mingw32 环境下，执行 make

生成 ffjpeg.dll 和 ffjpeg.exe

测试：
1. 编码 ffjpeg -e test.bmp 生成 encode.jpg 用图片浏览器查看
2. 解码 ffjpeg -d test.jpg 生成 decode.bmp 用图片浏览器查看

**Comment by huliangxiao** [comment]
请问为什么生成的encode.jpg只有1KB，打不开，test.bmp和test.jpg放哪了

**Comment by rockcarry** [comment]
放哪里都可以，命令行参数传入文件路径
你看看 main 函数怎么写就知道啊

**Comment by tangxu00** [comment]
我windows下没有安装gcc，我在linux下重新编写了Makefile，ffjpeg -e test.bmp得到的jpeg文件确实只有605个字节。在vs2013中运行得到的结果也是一样的。您知道问题出在哪里吗？

**Comment by rockcarry** [comment]
只支持 24bit 真彩色的 bmp 文件

**Comment by huliangxiao** [comment]
我在mingw下，随便找了一张jpg，用它作为jpg输入得到bmp文件，再用这个bmp作为输入，bmp有2400KB左右，得到的jpg文件有300KB

**Comment by rockcarry** [comment]
有问题吗？

**Comment by huliangxiao** [comment]
没有的，我只是说下这么弄就行了，谢谢大佬！在读你的代码，希望后面出现的问题大佬能解惑。

**Comment by rockcarry** [comment]
ok


好

**Comment by checko** [comment]
的確，因為在 linux 下 這格makefile 不能使用，
所以改用...

在 mingw 和 linux 下
gcc -o ffjpeg bitstr.c bmp.c color.c dct.c ffjpeg.c huffman.c jfif.c quant.c zigzag.c
都可以編譯成功，但是 mingw 下 jpeg encode 是成功的，在linux 下 jpeg encode 出錯的東西。
linux 下 ffjpeg encode 出來的jpg file, 用 mediainfo 看資訊是錯的:

General
Complete name                            : encode.jpg
Format                                   : JPEG
File size                                : 605 Bytes

Image
Format                                   : JPEG
Width                                    :  pixel0
Height                                   : 2 834 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 605 Bytes (100%)

**Comment by rockcarry** [comment]
@checko 是 64bit 编译器的问题，刚提交了代码，已经解决你说的问题。

**Comment by checko** [comment]
謝謝，成功了。
