### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by zvezdochiot** [rockcarry/ffjpeg#18]
https://github.com/rockcarry/ffjpeg/blob/master/LICENSE (GPL-3.0)

Maybe change to: https://github.com/ImageProcessing-ElectronicPublications/jpegrescan-perl/blob/master/LICENSE (PDM-1.0)?

**Comment by rockcarry** [comment]
sorry, source code of this project now is publiced by GPLv3.
and I haven't thought of any reason to change this license yet.

**Comment by zvezdochiot** [comment]
Ok.
