### ISSUE TITLE
关于 DCT 不同实现版本问题

### ISSUE THREAD

**Issue by binglingziyu** [rockcarry/ffjpeg#19]
![WechatIMG368](https://user-images.githubusercontent.com/6101838/75503755-89bc8a00-5a11-11ea-84d0-6db3346a7a2b.jpeg)

> 数学表达式版本生成的是预期的图片，是我使用方式有问题吗？

## 快速的整数运算版本使用方式

```
init_dct_module();

int block_dct[64] = ***
fdct2d8x8(block_dct, NULL);
````

## 数学表达式版本使用方式

```
int block_dct[64] = ***
fdct2d8x8(block_dct);
```

**Comment by rockcarry** [comment]
你把原始的 bmp图片给我，我编码测试下

**Comment by binglingziyu** [comment]
@rockcarry 

我用的方式是：代码生成 RGB 数据，然后用 ffjpeg 编码成 JPEG 图片

[这里是我的代码](https://github.com/rockcarry/ffjpeg/files/4271797/rgb-to-jpeg.zip)

**Comment by rockcarry** [comment]
你写个单元测试程序，对两个版本的 fdct2d8x8 做下测试看看。

**Comment by rockcarry** [comment]
刚看了下代码，快速算法接收的的是，fixed q2 的定点数。你把yuv数据左移2位应该就ok了。
