### ISSUE TITLE
关于Huffman编码

### ISSUE THREAD

**Issue by huliangxiao** [rockcarry/ffjpeg#2]
你好，我想问一下，每张图片的Huffman表是不一样的，对吧？并没有一种定式的Huffman编码表，都是进行压缩时利用编码规则生成一张，再添加进去的对吗？

**Comment by rockcarry** [comment]
JPEG 标准里面，规定了推荐的 huffman 表，这个可以拿来直接用。
如果不用这个推荐的 huffman 表，就需要自己重新统计所有码字的出现频率，然后生成 huffman 表。这样的好处是，可以得到更好的压缩率，缺点当然就是更加麻烦，编码时也更加耗时。
我的 ffjpeg 的实现里面，是直接用的 JPEG 标准推荐的 huffman 表。
