### ISSUE TITLE
在ubantu1604上无法正常产生图像

### ISSUE THREAD

**Issue by wiyglm** [rockcarry/ffjpeg#30]
安装之后按照所给格式处理jpg图片，得到的bmp文件只有文件头，大小为54字节；处理bmp图片也不能得到jpg图片，这是怎么回事呢？

**Comment by rockcarry** [comment]
commit dc1186807ec7466923af3ca60fd10c4a6a36b307
Author: chenk <chenk@apical.com.cn>
Date:   Mon Aug 3 03:56:23 2020 +0000

    fix issue #30


这个提交点修复了这个问题

**Comment by wiyglm** [comment]
> commit [dc11868](https://github.com/rockcarry/ffjpeg/commit/dc1186807ec7466923af3ca60fd10c4a6a36b307)
> 作者：chenk [chenk@apical.com.cn](mailto:chenk@apical.com.cn)
> 日期：2020年8月3日星期一03:56:23 2020 +0000
> 
> ```
> fix issue #30
> ```
> 
> 这个提交点修复了这个问题

用最新版本进行测试处理了几张图片，没有产生错误，可以正常运行。谢谢。
