### ISSUE TITLE
關於圖片的輸入檔案的限制

### ISSUE THREAD

**Issue by alanqq0624** [rockcarry/ffjpeg#32]
想請問關於輸入檔案的限制。
我個人嘗試了多個檔案，包含.jpg與.bmp檔，
兩者通過-d與-e後，有時候無法正常轉換圖片。
我在此篇的wiki中有看到說 bmp只支援24bit bmp ，
但是.jpg檔有相關限制嗎?

**Comment by rockcarry** [comment]
.jpg 档的编码方式也有不同的，目前支持了 baseline
所以不能保证全部的 .jpg 都能正确解码

**Comment by alanqq0624** [comment]
好的謝謝
我再去研究看看
