### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by Mainvooid** [rockcarry/ffjpeg#8]
void zigzag_encode(int *data)
{
    int buf[64], i;
    for (i=0; i<64; i++) buf [i] = data[ZIGZAG[i]];
    for (i=0; i<64; i++) data[i] = buf[i];
}

上面这个函数似乎是解码时用到的？解码时Z形扫描量化表。

**Comment by rockcarry** [comment]
这个是做 zigzag 编码
